# Maple Blog Production Docker Compose 配置
# 依赖外部数据库与 Redis，通过环境变量传入

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${PUBLIC_API_ORIGIN:-http://localhost:5000}
      - VITE_NODE_ENV=production
    depends_on:
      - backend
    networks:
      - maple-blog-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Database__Provider=${DATABASE_PROVIDER:-PostgreSQL}
      - Database__ConnectionStrings__PostgreSQL=${POSTGRES_CONNECTION_STRING}
      - Redis__ConnectionString=${REDIS_CONNECTION_STRING}
      - JWT__SecretKey=${JWT_SECRET_KEY}
      - JWT__Issuer=${JWT_ISSUER:-MapleBlog}
      - JWT__Audience=${JWT_AUDIENCE:-MapleBlog.Users}
    networks:
      - maple-blog-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  maple-blog-network:
    driver: bridge
