# Maple Blog Docker Compose 配置
# 开发环境使用

version: '3.8'

services:
  # 前端应用 - React 19
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ENVIRONMENT=development
    depends_on:
      - backend
    networks:
      - maple-blog-network
    restart: unless-stopped

  # 后端API - .NET 10
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - Database__Provider=SQLite
      - Database__ConnectionStrings__SQLite=Data Source=data/blog_dev.db
      - Redis__ConnectionString=redis:6379
      - JWT__SecretKey=maple-blog-development-secret-key-256-bits-long
      - JWT__Issuer=MapleBlog.Dev
      - JWT__Audience=MapleBlog.Dev.Users
    depends_on:
      - redis
    networks:
      - maple-blog-network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - maple-blog-network
    restart: unless-stopped

  # PostgreSQL 数据库 (可选，用于测试生产数据库)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maple_blog_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - maple-blog-network
    restart: unless-stopped

  # Mailhog (开发环境邮件测试)
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP端口
      - "8025:8025"  # Web UI端口
    networks:
      - maple-blog-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  maple-blog-network:
    driver: bridge