# Maple Blog Docker Compose 配置
# 开发环境使用

services:
  # 前端应用 - React 19
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_NODE_ENV=development
    depends_on:
      - backend
    networks:
      - maple-blog-network
    restart: unless-stopped

  # 后端API - .NET 9
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Database__Provider=${DATABASE_PROVIDER:-SQLite}
      - Database__ConnectionStrings__SQLite=${DATABASE_CONNECTION_SQLITE:-Data Source=data/blog_dev.db}
      - Database__ConnectionStrings__PostgreSQL=${DATABASE_CONNECTION_POSTGRESQL:-}
      - Redis__ConnectionString=${REDIS_CONNECTION_STRING:-localhost:6379}
      - JWT__SecretKey=${JWT_SECRET_KEY:-maple-blog-development-secret-key-256-bits-long}
      - JWT__Issuer=${JWT_ISSUER:-MapleBlog.Dev}
      - JWT__Audience=${JWT_AUDIENCE:-MapleBlog.Dev.Users}
    networks:
      - maple-blog-network
    restart: unless-stopped

  # Mailhog (开发环境邮件测试)
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP端口
      - "8025:8025"  # Web UI端口
    networks:
      - maple-blog-network
    restart: unless-stopped

networks:
  maple-blog-network:
    driver: bridge
