# Maple Blog Admin Docker Compose（精简版）
# 提供管理后台所需的最小运行集

services:
  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
      target: production
    ports:
      - "3100:80"
    environment:
      - VITE_API_URL=/api
      - VITE_NODE_ENV=production
    depends_on:
      - admin-backend
    networks:
      - maple-blog-admin
    restart: unless-stopped

  admin-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
      args:
        - PROJECT_NAME=MapleBlog.Admin
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Database__Provider=${ADMIN_DATABASE_PROVIDER:-PostgreSQL}
      - Database__ConnectionStrings__PostgreSQL=${ADMIN_POSTGRES_CONNECTION_STRING}
      - Redis__ConnectionString=${ADMIN_REDIS_CONNECTION_STRING}
      - JWT__SecretKey=${ADMIN_JWT_SECRET_KEY}
      - JWT__Issuer=${ADMIN_JWT_ISSUER:-MapleBlog.Admin}
      - JWT__Audience=${ADMIN_JWT_AUDIENCE:-MapleBlog.Admin.Users}
    networks:
      - maple-blog-admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  maple-blog-admin:
    driver: bridge
